const TENNIS_SHEET_ID="1iVX-93u-ydRftXX9PsBV0Cq0Q77084ZvRKxAem9tDuE";
const REFRESH_MS=2*60*1000;
const TABLES={fixtures:{name:"Results Entry",range:"A1:W1000"},standings:{name:"League Standings",range:"A1:J1000"}};
const CLUB_DIRECTORY_URL="https://www.cttennis.co.za/2025/Resources/Booklet%202025-2026.pdf";
const CLUB_IDENTITIES=[
 {name:"Bellville",mark:"BLV"},{name:"Bergvliet",mark:"BVT",href:"https://bergvliet-tennis.co.za/"},{name:"Bonteheuwel",mark:"BHW"},
 {name:"CPUT",mark:"CPUT",logo:"https://cumulusassociation.org/wp-content/uploads/2021/10/Cape-Peninsula-_logo-vertical.png",href:"https://www.cput.ac.za/"},
 {name:"Camps Bay",mark:"CB"},{name:"Chrismar",mark:"CHR"},{name:"Claremont",mark:"CTC",logo:"https://claremonttennis.co.za/wp-content/uploads/claremonth-tennis-club-cape-town-logo-white-200.png",href:"https://claremonttennis.co.za/"},
 {name:"Constantia",mark:"CST",href:"https://constantiatennisclub.co.za/"},{name:"Edgemead",mark:"EDG"},{name:"Eversdal",mark:"EVD"},
 {name:"Fish Hoek",mark:"FHTC",href:"https://www.fhtc.co.za/"},{name:"Fresnaye",mark:"FRS"},{name:"Gardens",mark:"GLTC"},{name:"Glen",mark:"GCC",href:"https://www.glenclub.co.za/"},
 {name:"Green Point",mark:"GPTC",logo:"https://greenpointtennis.co.za/images/history/new_logo.jpg",href:"https://greenpointtennis.co.za/"},
 {name:"Kenridge",mark:"KEN"},{name:"Kelvin Grove",mark:"KG",href:"https://www.kelvingrove.co.za/"},{name:"Khayelitsha",mark:"KHA"},{name:"Langa",mark:"LTC"},
 {name:"Llandudno",mark:"LLT"},{name:"Meadowridge",mark:"MTC",href:"https://meadowridgetennisclub.co.za/"},{name:"Milnerton",mark:"MTC",href:"https://www.milnertontennisclub.co.za/"},
 {name:"Mitchells Plain",mark:"MPTC"},{name:"Monte Vista",mark:"MVTC"},{name:"Old Mutual",mark:"OMTC"},{name:"Orangia",mark:"OTC"},{name:"Parow",mark:"PTC"},
 {name:"Pinelands",mark:"PTC",href:"https://www.pinelandstennisclub.co.za/"},{name:"Plumstead",mark:"PLTC"},{name:"TAB",mark:"TAB"},{name:"Tornadoes",mark:"TTTC"},
 {name:"UCT",mark:"UCT",href:"https://sport.uct.ac.za/"},{name:"UWC",mark:"UWC",href:"https://www.uwc.ac.za/"},{name:"WPCC",mark:"WPCC",href:"https://www.wpcc.co.za/"},
 {name:"Welgemoed",mark:"WTC"},{name:"Wynberg",mark:"WLTC"}
];
const FALLBACK_FIXTURES=[
 ["F0001","05-Sep-2026","Ladies Doubles 1","Doubles","Claremont LDA","Fresnaye LDA","","","","","","","","","","","","","","Scheduled"],
 ["F0002","05-Sep-2026","Ladies Doubles 1","Doubles","Glen LDA","Kenridge LDA","","","","","","","","","","","","","","Scheduled"],
 ["F0003","05-Sep-2026","Ladies Doubles 1","Doubles","Old Mutual LDA","Meadowridge LDA","","","","","","","","","","","","","","Scheduled"],
 ["F0004","05-Sep-2026","Ladies Doubles 1","Doubles","Pinelands LDA","Tornadoes LDA","","","","","","","","","","","","","","Scheduled"],
 ["F0059","05-Sep-2026","Mens Premier","Singles","Constantia MSA","Camps Bay MSA","","","","","","","","","","","","","","Scheduled"],
 ["F0060","05-Sep-2026","Mens Premier","Singles","Glen MSA","Chrismar MSA","","","","","","","","","","","","","","Scheduled"],
 ["F0063","05-Sep-2026","Mens Singles 1","Singles","Camps Bay MSB","Claremont MSA","","","","","","","","","","","","","","Scheduled"],
 ["F0064","05-Sep-2026","Mens Singles 1","Singles","Edgemead MSA","Gardens MSA","","","","","","","","","","","","","","Scheduled"]
];
const FALLBACK_STANDINGS={
 "Ladies Doubles 1":["Claremont LDA","Fresnaye LDA","Glen LDA","Kenridge LDA","Meadowridge LDA","Old Mutual LDA","Pinelands LDA","Tornadoes LDA"].map(team=>["1",team,"7","0","0","7","0","0","0","0"]),
 "Mens Doubles 1":["Claremont MDA","Constantia MDA","Edgemead MDA","Fish Hoek MDA","Fresnaye MDA","Kenridge MDA","Llandudno MDA","Meadowridge MDA"].map(team=>["1",team,"7","0","0","7","0","0","0","0"])
};
const state={fixtures:[],standings:{},view:"fixtures",gender:"all",format:"all",club:"all",division:"all",matchday:"all",standingGender:"ladies",standingDivision:"",liveClub:"all",visible:12};
function cell(row,index){const value=row?.c?.[index];return String(value?.f??value?.v??"").trim()}
function loadTable({name,range}){return new Promise((resolve,reject)=>{const callbackName=`_cttSheet${Date.now()}${Math.random().toString(36).slice(2)}`;const script=document.createElement("script");let settled=false;const finish=(error,table)=>{if(settled)return;settled=true;window.clearTimeout(timeout);script.remove();delete globalThis[callbackName];error?reject(error):resolve(table)};const timeout=window.setTimeout(()=>finish(new Error(`Timed out loading ${name}`)),15000);globalThis[callbackName]=response=>response?.table&&response?.status!=="error"?finish(null,response.table):finish(new Error(`Could not read ${name}`));script.onerror=()=>finish(new Error(`Could not connect to ${name}`));const query=new URLSearchParams({sheet:name,range,headers:"0",tqx:`out:json;responseHandler:${callbackName}`,cache:String(Date.now())});script.src=`https://docs.google.com/spreadsheets/d/${TENNIS_SHEET_ID}/gviz/tq?${query}`;document.head.append(script)})}
function parseDate(value){const match=String(value).match(/^(\d{1,2})-([A-Za-z]{3})-(\d{4})$/);if(!match)return null;const months={Jan:0,Feb:1,Mar:2,Apr:3,May:4,Jun:5,Jul:6,Aug:7,Sep:8,Oct:9,Nov:10,Dec:11};const month=months[match[2]];return month===undefined?null:new Date(Number(match[3]),month,Number(match[1]))}
function genderKey(division){const value=String(division).toLowerCase();if(value.startsWith("lad"))return"ladies";if(value.startsWith("men"))return"mens";return"other"}
function fixtureFromValues(values){return{id:values[0],date:values[1],division:values[2],format:values[3],home:values[4],away:values[5],homeMatches:values[6],awayMatches:values[7],homeSets:values[8],awaySets:values[9],result:values[10],homePts:values[17],awayPts:values[18],status:values[19]||"Scheduled"}}
function parseFixtures(table){return(table.rows||[]).map(row=>Array.from({length:20},(_,index)=>cell(row,index))).filter(values=>/^F\d+$/i.test(values[0])&&values[4]&&values[5]).map(fixtureFromValues)}
function parseStandings(table,divisionOrder=[]){const groups={};let division="";let groupIndex=-1;(table.rows||[]).forEach(row=>{const values=Array.from({length:10},(_,index)=>cell(row,index));const first=values[0];if(values[1]==="Team"){groupIndex++;division=divisionOrder[groupIndex]||"";if(division)groups[division]||=[];return}if(first&&!values[1]&&first!=="Rank"&&!/live standings|updates automatically/i.test(first)){division=first;groups[division]||=[];return}if(division&&/^\d+$/.test(first)&&values[1])groups[division].push(values)});return Object.fromEntries(Object.entries(groups).filter(([,rows])=>rows.length))}
function valuesFixtureFallback(){return FALLBACK_FIXTURES.map(fixtureFromValues)}
function normaliseStandings(groups){return Object.fromEntries(Object.entries(groups).map(([division,rows])=>[division,rows.map(values=>Array.isArray(values)?{rank:values[0],team:values[1],played:values[2],won:values[3],drawn:values[4],lost:values[5],setsFor:values[6],setsAgainst:values[7],setsDiff:values[8],points:values[9]}:values)]))}
function standingNumber(value){const number=Number(String(value??"").trim().replace("−","-").replace(",","."));return Number.isFinite(number)?number:0}
function sortedStandingRows(rows){return rows.map((row,index)=>({row,index})).sort((a,b)=>standingNumber(b.row.points)-standingNumber(a.row.points)||standingNumber(b.row.setsDiff)-standingNumber(a.row.setsDiff)||standingNumber(a.row.rank)-standingNumber(b.row.rank)||a.index-b.index).map(({row})=>row)}
function standingsFallback(){return normaliseStandings(FALLBACK_STANDINGS)}
function el(tag,className,text){const node=document.createElement(tag);if(className)node.className=className;if(text!==undefined)node.textContent=text;return node}
function clubCarouselCard(club,index,isDuplicate=false){const link=el("a","club-logo-card");link.href=club.href||CLUB_DIRECTORY_URL;link.target="_blank";link.rel="noopener";link.title=`${club.name} — ${club.href?"official website":"Cape Town Tennis club directory"}`;link.style.setProperty("--club-tone",String(index%6));if(isDuplicate){link.setAttribute("aria-hidden","true");link.tabIndex=-1}const badge=el("span","club-logo-card__mark");const fallback=el("b","",club.mark);badge.append(fallback);if(club.logo){const image=new Image();image.src=club.logo;image.alt="";image.loading="lazy";image.decoding="async";image.addEventListener("load",()=>badge.classList.add("has-image"));image.addEventListener("error",()=>image.remove());badge.prepend(image)}const copy=el("span","club-logo-card__copy");copy.append(el("strong","",club.name),el("small","",club.logo?"Official mark":"Tennis club"));link.append(badge,copy);return link}
function renderClubCarousel(){const track=document.querySelector("[data-club-track]");if(!track)return;const groups=[false,true].map(isDuplicate=>{const group=el("div","club-carousel__group");if(isDuplicate)group.setAttribute("aria-hidden","true");CLUB_IDENTITIES.forEach((club,index)=>group.append(clubCarouselCard(club,index,isDuplicate)));return group});track.replaceChildren(...groups)}
function formatDate(value,short=false){const date=parseDate(value);if(!date)return value||"Date TBC";return new Intl.DateTimeFormat("en-ZA",short?{day:"2-digit",month:"short"}:{weekday:"short",day:"2-digit",month:"short",year:"numeric"}).format(date)}
function completed(fixture){return/complete|played|final/i.test(fixture.status)||fixture.result||fixture.homeMatches!==""||fixture.awayMatches!==""}
function matchFilter(fixture){if(state.gender!=="all"&&genderKey(fixture.division)!==state.gender)return false;if(state.format!=="all"&&fixture.format!==state.format)return false;if(state.club!=="all"&&clubName(fixture.home)!==state.club&&clubName(fixture.away)!==state.club)return false;if(state.division!=="all"&&fixture.division!==state.division)return false;if(state.matchday!=="all"&&fixture.date!==state.matchday)return false;return state.view==="results"?completed(fixture):!completed(fixture)}
function matchCard(fixture){const isComplete=completed(fixture);const card=el("article","match-card");const top=el("div","match-card__top");top.append(el("span","match-card__id",fixture.id),el("span",`status-pill${isComplete?" status-pill--completed":""}`,isComplete?"Completed":fixture.status));const division=el("p","match-card__division",`${fixture.division} · ${fixture.format}`);const date=el("h3","match-card__date",formatDate(fixture.date));const teams=el("div","match-card__teams");[[fixture.home,fixture.homeMatches],[fixture.away,fixture.awayMatches]].forEach(([name,score])=>{const row=el("div","match-team");row.append(el("span","",name),el("b","",isComplete?(score||"–"):""));teams.append(row)});const footer=el("div","match-card__footer");footer.append(el("span","",isComplete&&fixture.homeSets!==""?`Sets ${fixture.homeSets}–${fixture.awaySets}`:"Official league fixture"),el("strong","",isComplete&&fixture.homePts!==""?`Pts ${fixture.homePts}–${fixture.awayPts}`:"Cape Town"));card.append(top,division,date,teams,footer);return card}
function emptyState(title,copy,marker="↗"){const empty=el("div","empty-state");empty.append(el("span","",marker),el("h3","",title),el("p","",copy));return empty}
function clubName(team){return String(team||"").replace(/\s+[LM][DS][A-Z]\s*$/i,"").replace(/\s+/g," ").trim()}
function competingClubs(){return[...new Set(state.fixtures.flatMap(fixture=>[clubName(fixture.home),clubName(fixture.away)]).filter(club=>club&&!/^bye$/i.test(club)))].sort((a,b)=>a.localeCompare(b))}
function updateFixtureClubFilter(){const select=document.querySelector('[data-filter="club"]');if(!select)return;const clubs=competingClubs();const selected=state.club;select.replaceChildren(new Option("All clubs","all"));clubs.forEach(club=>select.add(new Option(club,club)));state.club=clubs.includes(selected)?selected:"all";select.value=state.club}
function fixtureIsLive(fixture){return/live|in progress|on court|playing/i.test(fixture.status)}
function updateLiveClubFilter(){const select=document.querySelector("[data-live-club]");if(!select)return;const clubs=competingClubs();const selected=state.liveClub;select.replaceChildren(new Option("All competing clubs","all"));clubs.forEach(club=>select.add(new Option(club,club)));state.liveClub=clubs.includes(selected)?selected:"all";select.value=state.liveClub}
function liveMatchContent(fixture){const body=el("div","live-court__match");const meta=el("div","live-court__match-meta");meta.append(el("span","",fixture.division),el("strong","",formatDate(fixture.date)));body.append(meta);[[fixture.home,fixture.homeMatches],[fixture.away,fixture.awayMatches]].forEach(([team,score])=>{const row=el("div","live-court__team");row.append(el("strong","",team),el("b","",score||"–"));body.append(row)});body.append(el("small","",fixture.homeSets!==""?`Sets: ${fixture.homeSets}–${fixture.awaySets}`:"Live score feed connected"));return body}
function livePlaceholder(courtNumber,clubLabel){const body=el("div","live-court__placeholder");body.append(el("span","",String(courtNumber)),el("h3","","Waiting for a live match"),el("p","",clubLabel==="All competing clubs"?"This court will update automatically once a match goes live.":`No live ${clubLabel} score is available on this court yet.`));return body}
function renderLiveScores(){const cards=[...document.querySelectorAll("[data-live-court]")];if(!cards.length)return;const clubLabel=state.liveClub==="all"?"All competing clubs":state.liveClub;document.querySelector("[data-live-club-label]").textContent=clubLabel;const live=state.fixtures.filter(fixture=>fixtureIsLive(fixture)&&(state.liveClub==="all"||clubName(fixture.home)===state.liveClub||clubName(fixture.away)===state.liveClub));cards.forEach((card,index)=>{const fixture=live[index];const status=card.querySelector("header i");card.classList.toggle("is-live",Boolean(fixture));status.textContent=fixture?"Live":"Waiting";card.lastElementChild.replaceWith(fixture?liveMatchContent(fixture):livePlaceholder(index+1,clubLabel))})}
function availableDates(){return[...new Set(state.fixtures.filter(fixture=>{if(state.gender!=="all"&&genderKey(fixture.division)!==state.gender)return false;if(state.format!=="all"&&fixture.format!==state.format)return false;if(state.club!=="all"&&clubName(fixture.home)!==state.club&&clubName(fixture.away)!==state.club)return false;if(state.division!=="all"&&fixture.division!==state.division)return false;return state.view==="results"?completed(fixture):!completed(fixture)}).map(fixture=>fixture.date))].sort((a,b)=>(parseDate(a)||0)-(parseDate(b)||0))}
function renderMatchdays(){const strip=document.querySelector("[data-matchdays]");const dates=availableDates();if(state.matchday!=="all"&&!dates.includes(state.matchday))state.matchday="all";strip.replaceChildren();const all=el("button","");all.type="button";all.setAttribute("aria-pressed",String(state.matchday==="all"));all.append(el("b","","All dates"),el("span","",`${dates.length} matchdays`));all.addEventListener("click",()=>{state.matchday="all";state.visible=12;renderMatches()});strip.append(all);dates.forEach(value=>{const button=el("button","");button.type="button";button.setAttribute("aria-pressed",String(state.matchday===value));button.append(el("b","",formatDate(value,true)),el("span","","Matchday"));button.addEventListener("click",()=>{state.matchday=value;state.visible=12;renderMatches()});strip.append(button)})}
function renderMatches(){renderMatchdays();const grid=document.querySelector("[data-match-grid]");const loadMore=document.querySelector("[data-load-more]");const filtered=state.fixtures.filter(matchFilter);grid.replaceChildren();if(!filtered.length){grid.append(emptyState(state.view==="results"?"No completed results yet":"No fixtures match these filters",state.view==="results"?"The 2026 season begins on 5 September. Results will appear here automatically once entered in the official sheet.":"Try another division, format or matchday.",state.view==="results"?"✓":"⌕"))}else filtered.slice(0,state.visible).forEach(fixture=>grid.append(matchCard(fixture)));loadMore.hidden=filtered.length<=state.visible;loadMore.textContent=`Show more ${state.view}`;document.querySelector("[data-fixture-count]").textContent=state.fixtures.filter(f=>!completed(f)).length;document.querySelector("[data-result-count]").textContent=state.fixtures.filter(completed).length}
function updateDivisionFilter(){const select=document.querySelector('[data-filter="division"]');const selected=state.division;const divisions=[...new Set(state.fixtures.filter(f=>state.gender==="all"||genderKey(f.division)===state.gender).map(f=>f.division))].sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}));select.replaceChildren(new Option("All divisions","all"));divisions.forEach(division=>select.add(new Option(division,division)));state.division=divisions.includes(selected)?selected:"all";select.value=state.division}
function standingsForGender(gender){return Object.keys(state.standings).filter(division=>genderKey(division)===gender).sort((a,b)=>a.localeCompare(b,undefined,{numeric:true}))}
function renderStandingControls(){const divisions=standingsForGender(state.standingGender);if(!divisions.includes(state.standingDivision))state.standingDivision=divisions[0]||"";const select=document.querySelector("[data-standing-division]");select.replaceChildren();divisions.forEach(division=>select.add(new Option(division,division)));if(!divisions.length)select.add(new Option("No divisions available",""));select.value=state.standingDivision}
function renderStandings(){renderStandingControls();const division=state.standingDivision;const rows=sortedStandingRows(state.standings[division]||[]);document.querySelector("[data-standing-title]").textContent=division||"League standings";document.querySelector("[data-standing-team-count]").textContent=`${rows.length} ${rows.length===1?"team":"teams"}`;const table=document.querySelector("[data-standings-table]");const head=el("div","standings-row standings-row--head");["Pos","Team","Pld","W","D","L","SD","Pts"].forEach(label=>head.append(el("span","",label)));table.replaceChildren(head);if(!rows.length){table.append(el("div","standings-empty","Standings will appear as soon as the live sheet is available."));return}rows.forEach(row=>{const line=el("div","standings-row");const rank=el("span","standings-row__rank");rank.append(el("b","",row.rank));line.append(rank,el("span","standings-row__team",row.team),el("span","",row.played),el("span","",row.won),el("span","",row.drawn),el("span","",row.lost),el("span","",row.setsDiff),el("span","standings-row__points",row.points));table.append(line)})}
function updateStats(){const teams=new Set(state.fixtures.flatMap(fixture=>[fixture.home,fixture.away]).filter(team=>!/^bye$/i.test(team)));const divisions=new Set(state.fixtures.map(fixture=>fixture.division));document.querySelector('[data-stat="clubs"]').textContent=teams.size||"—";document.querySelector('[data-stat="divisions"]').textContent=divisions.size||"—";document.querySelector('[data-stat="fixtures"]').textContent=state.fixtures.length||"—";updateFixtureClubFilter();updateLiveClubFilter();renderLiveScores()}
function setSheetStatus(message,status){const target=document.querySelector("[data-sheet-status]");target.dataset.state=status;target.querySelector("span").textContent=message}
async function refreshData(){const results=await Promise.allSettled([loadTable(TABLES.fixtures),loadTable(TABLES.standings)]);let liveParts=0;if(results[0].status==="fulfilled"){const fixtures=parseFixtures(results[0].value);if(fixtures.length){state.fixtures=fixtures;liveParts++}}if(!state.fixtures.length)state.fixtures=valuesFixtureFallback();if(results[1].status==="fulfilled"){const divisionOrder=[...new Set(state.fixtures.map(fixture=>fixture.division))];const standings=normaliseStandings(parseStandings(results[1].value,divisionOrder));if(Object.keys(standings).length){state.standings=standings;liveParts++}}if(!Object.keys(state.standings).length)state.standings=standingsFallback();updateDivisionFilter();updateStats();renderMatches();renderStandings();const time=new Intl.DateTimeFormat("en-ZA",{hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date());setSheetStatus(liveParts===2?`Live sheet updated at ${time}`:"Showing a verified sheet snapshot; live refresh will retry",liveParts===2?"success":"warning")}
function bindControls(){document.querySelectorAll("[data-match-view]").forEach(button=>button.addEventListener("click",()=>{state.view=button.dataset.matchView;state.matchday="all";state.visible=12;document.querySelectorAll("[data-match-view]").forEach(item=>item.setAttribute("aria-selected",String(item===button)));renderMatches()}));document.querySelectorAll("[data-filter]").forEach(select=>select.addEventListener("change",()=>{state[select.dataset.filter]=select.value;state.matchday="all";state.visible=12;if(select.dataset.filter==="gender")updateDivisionFilter();renderMatches()}));document.querySelector("[data-load-more]").addEventListener("click",()=>{state.visible+=12;renderMatches()});document.querySelectorAll("[data-standing-gender]").forEach(button=>button.addEventListener("click",()=>{state.standingGender=button.dataset.standingGender;state.standingDivision="";document.querySelectorAll("[data-standing-gender]").forEach(item=>item.setAttribute("aria-selected",String(item===button)));renderStandings()}));document.querySelector("[data-standing-division]").addEventListener("change",event=>{state.standingDivision=event.target.value;renderStandings()});document.querySelector("[data-results-shortcut]").addEventListener("click",()=>{state.view="results";state.matchday="all";document.querySelectorAll("[data-match-view]").forEach(item=>item.setAttribute("aria-selected",String(item.dataset.matchView==="results")));renderMatches()});const toggle=document.querySelector("[data-menu-toggle]");const nav=document.querySelector("[data-mobile-nav]");toggle.addEventListener("click",()=>{const open=toggle.getAttribute("aria-expanded")==="true";toggle.setAttribute("aria-expanded",String(!open));nav.hidden=open});nav.querySelectorAll("a").forEach(link=>link.addEventListener("click",()=>{toggle.setAttribute("aria-expanded","false");nav.hidden=true}))}
function updateTime(){const target=document.querySelector("[data-local-time]");const time=new Intl.DateTimeFormat("en-ZA",{timeZone:"Africa/Johannesburg",hour:"2-digit",minute:"2-digit",hour12:false}).format(new Date());target.textContent=`${time} SAST`}
function bindLiveScoreControls(){const select=document.querySelector("[data-live-club]");if(!select)return;select.addEventListener("change",()=>{state.liveClub=select.value;renderLiveScores()})}
function bindNavigationActiveState(){const links=[...document.querySelectorAll('.site-nav a[href^="#"]:not([hidden]),.mobile-nav a[href^="#"]:not([hidden])')];const sectionIds=[...new Set(links.map(link=>link.getAttribute("href").slice(1)))];const sections=sectionIds.map(id=>document.getElementById(id)).filter(Boolean);if(!links.length||!sections.length)return;let queued=false;const activate=id=>{links.forEach(link=>{const active=link.getAttribute("href")===`#${id}`;link.classList.toggle("is-active",active);if(active)link.setAttribute("aria-current","location");else link.removeAttribute("aria-current")})};const update=()=>{queued=false;const header=document.querySelector("[data-header]");const marker=(header?.offsetHeight||0)+Math.min(180,window.innerHeight*.24);let active="";sections.forEach(section=>{if(section.getBoundingClientRect().top<=marker)active=section.id});if(window.scrollY+window.innerHeight>=document.documentElement.scrollHeight-4)active=sections.at(-1)?.id||active;activate(active)};const requestUpdate=()=>{if(queued)return;queued=true;requestAnimationFrame(update)};links.forEach(link=>link.addEventListener("click",()=>activate(link.getAttribute("href").slice(1))));update();window.addEventListener("scroll",requestUpdate,{passive:true});window.addEventListener("resize",requestUpdate,{passive:true});window.addEventListener("hashchange",requestUpdate)}
function initialiseHeroParallax(){const hero=document.querySelector(".hero");const image=document.querySelector(".hero__media");if(!hero||!image||window.matchMedia("(prefers-reduced-motion: reduce)").matches)return;let queued=false;const update=()=>{queued=false;const rect=hero.getBoundingClientRect();if(rect.bottom<=0||rect.top>=window.innerHeight)return;const passed=Math.max(0,-rect.top);const offset=Math.min(rect.height*.12,passed*.22);image.style.setProperty("--hero-parallax",`${offset.toFixed(1)}px`)};const requestUpdate=()=>{if(queued)return;queued=true;window.requestAnimationFrame(update)};update();window.addEventListener("scroll",requestUpdate,{passive:true});window.addEventListener("resize",requestUpdate,{passive:true})}
renderClubCarousel();bindControls();bindLiveScoreControls();bindNavigationActiveState();initialiseHeroParallax();updateTime();window.setInterval(updateTime,30000);refreshData();window.setInterval(()=>{if(!document.hidden)refreshData()},REFRESH_MS);document.addEventListener("visibilitychange",()=>{if(!document.hidden)refreshData()});
